name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.5
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  permission_handler: ^12.0.0+1
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  http: ^1.5.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
